//! # Multi-Agent Coding & Review Pipeline Example
//!
//! Demonstrates the use of [AgentDispatcher] to orchestrate collaborative agent loops.
//! A "coder" (ReAct agent) writes code, and a "reviewer" (Managed agent) analyzes it.
//!
//! Run with:
//! ```bash
//! cargo run --example multi_agent_coder
//! ```

use agent_rs::agent::dispatch::{
    AgentDispatcher, AgentInput, ManagedAgentDefinition, ReActAgentDefinition,
};
use agent_rs::agent::{ManagedExt, ReActExt};
use anyhow::{Result, bail};
use dotenvy::dotenv;
use rig_core::prelude::*;
use rig_core::providers::openai;
use std::env;

#[tokio::main]
async fn main() -> Result<()> {
    dotenv().ok();

    let chat_model_name =
        env::var("CHAT_MODEL").unwrap_or_else(|_| "google/gemma-4-e4b".to_string());
    let chat_base_url =
        env::var("CHAT_BASE_URL").unwrap_or_else(|_| "http://127.0.0.1:1234/v1".to_string());
    let api_key = match env::var("API_KEY") {
        Ok(k) if !k.is_empty() => k,
        _ => bail!("Missing API_KEY env var in .env (set it to your LLM provider key)"),
    };

    println!("Initializing Multi-Agent Coder Pipeline...");
    println!("  Model: {chat_model_name}");
    println!("  URL: {chat_base_url}");

    let chat_client = openai::CompletionsClient::builder()
        .base_url(chat_base_url)
        .api_key(api_key)
        .build()?;

    // 1. Build the Coder Agent (ReAct)
    let raw_coder = chat_client
        .agent(&chat_model_name)
        .preamble(
            "You are a Senior Rust Developer. \
            Your task is to write clean, idiomatic Rust code for the requested functionality. \
            Do not include explanations, only write the Rust code inside a markdown code block.",
        )
        .default_max_turns(2)
        .build();

    let coder_agent = raw_coder.react().max_cycles(5).build();

    let coder_def = ReActAgentDefinition::new(
        "coder".to_string(),
        vec!["development".to_string()],
        "Senior Rust Developer agent that writes clean code".to_string(),
        coder_agent,
    );

    // 2. Build the Reviewer Agent (Managed)
    let raw_reviewer = chat_client
        .agent(&chat_model_name)
        .preamble(
            "You are a Rust Code Reviewer. \
            Your task is to review the code provided by the coder. \
            Identify any performance, safety, or style issues. \
            If the code looks perfect, say 'APPROVED'. Otherwise, provide improvement feedback.",
        )
        .build();

    let reviewer_agent = raw_reviewer.managed().build();

    let reviewer_def = ManagedAgentDefinition::new(
        "reviewer".to_string(),
        vec!["quality_assurance".to_string()],
        "Rust Code Reviewer agent that reviews code quality".to_string(),
        reviewer_agent,
    );

    // 3. Register to Dispatcher
    let mut dispatcher = AgentDispatcher::new();
    dispatcher.register(Box::new(coder_def))?;
    dispatcher.register(Box::new(reviewer_def))?;

    // 4. Run the Pipeline
    let prompt = "Write a high-performance function in Rust to compute the Nth Fibonacci number.";
    println!("\nUser Request: \"{}\"", prompt);

    println!("\n[Dispatcher] Dispatching task to Coder...");
    let coder_output = dispatcher
        .dispatch(
            "coder",
            AgentInput {
                prompt: prompt.to_string(),
                context: None,
            },
        )
        .await?;

    println!("\n=== Code Generated by Coder ===\n{}", coder_output.answer);

    println!("\n[Dispatcher] Dispatching code to Reviewer...");
    let reviewer_output = dispatcher
        .dispatch(
            "reviewer",
            AgentInput {
                prompt: format!(
                    "Review this code:\n\n{}\n\nDoes it look correct, performant, and safe?",
                    coder_output.answer
                ),
                context: None,
            },
        )
        .await?;

    println!("\n=== Code Review Feedback ===\n{}", reviewer_output.answer);

    Ok(())
}
